### PR TITLE
ES6 - modules feature

### PR DESCRIPTION
**Pull request by Camilovelag**
Good morning/afternoon. 🌤️

This pull request is intended to split js features into modules for the awesome books project.

Changes made: 🔧

✔️ `package.json` was created.
✔️ `index.js`,  `index.css`, and `modules` folder were created.
✔️ `scripts.js` methods were split between `index.js` and `collection.js`.
✔️ Date and time feature was set up using [Luxon](https://moment.github.io/luxon/#/install?id=es6).

I am expecting feedback.

Regards! 😸

### CODE REVIEW

**Review by rotimiazeez — CHANGES_REQUESTED** [review]
# Hi @Camilovelag 👏🏽, 
## Good job so far! 👍🏽 
### Summary ♨️ 
- No Linter error ✔️ 
- Good and descriptive PR 💯 
- Good UI 👓 
- Good commit message(s) 👍🏽 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights


## Required Changes ♻️
_Check the comments under the review._
## Please make sure all your functions are changed to use the ES6(arrow function) 👍🏽 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Camilovelag** [comment]
> # Hi @Camilovelag 👏🏽,
> ## Good job so far! 👍🏽
> ### Summary ♨️
> * No Linter error ✔️
> * Good and descriptive PR 💯
> * Good UI 👓
> * Good commit message(s) 👍🏽
>   There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Please make sure all your functions are changed to use the ES6(arrow function) 👍🏽
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Camilovelag** [comment]
Hi @rotimiazeez 

Please, could you clarify the recommendation you give me? I've checked every file with `.js` extension, and `function` wasn't found (instead I've used ES6 arrow function syntax), except for `luxon.js`, but this file is a third-party element, so I think it is OK to keep the native function syntax used (besides the quantity of changes should be very high 😮‍💨 ):

index.js
image

collection.js
image

luxon.js
image

In case you were talking about specific code lines, please point out these ones to make the corresponding changes.

Regards 🐱

**Comment by Camilovelag** [comment]
Good morning/afternoon.
I sent you this second CR with no changes because I was waiting for an explanation about the change suggested by the previous code review with no answer (this thread, message on Slack).
Additional to this, to make sure I didn't miss something, I asked my morning group for a review, and no issues were found (check their comments [here](https://github.com/Camilovelag/Awesome_books/issues/6).
If you consider the change suggested by the previous code reviewer is correct, please point out in which line is displayed or a more specific explanation about that.
Regards.

**Review by DeliceLydia — APPROVED** [review]
## Hi @Camilovelag, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
